language: node_js
node_js:
  - 16.13.0
cache: npm
install:
  - npm install
script:
  - npm docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
  branch: vitepress
